export const bars = [
  { "quote": "Who's gonna carry the boats?", "author": "David Goggins" },
  { "quote": "You don't know me son.", "author": "David Goggins" },
  { "quote": "Light weight baby!", "author": "Ronnie Coleman" },
  { "quote": "Yeah buddy!", "author": "Ronnie Coleman" },
  { "quote": "Ain't nothin' but a peanut.", "author": "Ronnie Coleman" },
  { "quote": "Sleep is for the weak.", "author": "Eddie Hall" },
  { "quote": "That's a PR bro.", "author": "You?" },
  { "quote": "Chest up, hips back, rip it.", "author": "Mark Bell" },
  { "quote": "Stay hard.", "author": "David Goggins" },
  { "quote": "You are not tired, you just think you are.", "author": "David Goggins" },
  { "quote": "The last three or four reps is what makes the muscle grow.", "author": "Arnold Schwarzenegger" },
  { "quote": "Pain is temporary, glory is forever.", "author": "Arnold Schwarzenegger" },
  { "quote": "The iron never lies to you.", "author": "Henry Rollins" },
  { "quote": "Nobody ever got strong by thinking about it.", "author": "Jim Wendler" },
  { "quote": "You shall gain, but you shall pay with sweat, blood, and vomit.", "author": "Pavel Tsatsouline" },
  { "quote": "Everybody wants to be a bodybuilder but nobody wants to lift no heavy ass weights.", "author": "Ronnie Coleman" },
  { "quote": "The only bad workout is the one that didn't happen.", "author": "Ed Coan" },
  { "quote": "To be a champion, you must act like one.", "author": "Lou Ferrigno" },
  { "quote": "Strength is not a physical attribute, it's a state of mind.", "author": "Ed Coan" },
  { "quote": "There are no shortcuts. Everything is reps, reps, reps.", "author": "Arnold Schwarzenegger" },
  { "quote": "Stimulate, don't annihilate.", "author": "Lee Haney" },
  { "quote": "If you think lifting is dangerous, try being weak.", "author": "Mark Rippetoe" },
  { "quote": "I would rather be dead than ordinary.", "author": "Rich Piana" },
  { "quote": "Whatever it takes.", "author": "Rich Piana" },
  { "quote": "I don't care what you bench, how much do you curl?", "author": "Larry Scott" },
  { "quote": "The only way to prove you are a good sport is to lose.", "author": "Ernie Banks" },
  { "quote": "I train like an animal but eat like a king.", "author": "Dorian Yates" },
  { "quote": "You have to think it before you can do it.", "author": "Dorian Yates" },
  { "quote": "Suffer the pain of discipline or suffer the pain of regret.", "author": "CT Fletcher" },
  { "quote": "It's still your set!", "author": "CT Fletcher" },
  { "quote": "I command you to grow!", "author": "CT Fletcher" },
  { "quote": "Obsession is a word used by the lazy to describe the dedicated.", "author": "CT Fletcher" },
  { "quote": "If you have a body, you are an athlete.", "author": "Bill Bowerman" },
  { "quote": "The road to nowhere is paved with excuses.", "author": "Mark Bell" },
  { "quote": "Getting strong is simple, it just isn't easy.", "author": "Jim Wendler" },
  { "quote": "Embrace the suck.", "author": "David Goggins" },
  { "quote": "I never think about how much the bar weighs. I just think about moving it.", "author": "Stefi Cohen" },
  { "quote": "The only limitations are the ones you set yourself.", "author": "Stefi Cohen" },
  { "quote": "Be stronger than your excuses.", "author": "Karina Baymiller" },
  { "quote": "I don't train to look good. I train to be strong.", "author": "Maryana Naumova" },
  { "quote": "Strength is not gender specific.", "author": "Amber Weight" },
  { "quote": "Every rep is a choice.", "author": "Jennifer Thompson" },
  { "quote": "The platform doesn't care about your excuses.", "author": "Jennifer Thompson" },
  { "quote": "Train like a beast, look like a beauty.", "author": "Oksana Grishina" },
  { "quote": "Strong is the new everything.", "author": "Holley Mangold" },
  { "quote": "I don't count my reps. I only start counting when it burns.", "author": "Iris Kyle" },
  { "quote": "Champions aren't born, they're built.", "author": "Iris Kyle" },
  { "quote": "Pain is just weakness leaving the body, and I have a lot of weakness to get rid of.", "author": "Stefi Cohen" },
  { "quote": "I didn't come this far to only come this far.", "author": "Kara Bohigian" },
  { "quote": "If it was easy everyone would do it.", "author": "Amanda Lawrence" },
  { "quote": "I train for the person I want to become.", "author": "Jessica Buettner" },
  { "quote": "Doubt me, that's all the fuel I need.", "author": "Natalie Hanson" },
  { "quote": "Your comfort zone is a beautiful place but nothing grows there.", "author": "Summer Cook" },
  { "quote": "I don't sweat glitter, I sweat progress.", "author": "Tamara Walcott" },
]