name: Deploy static content to Pages
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: tracker-app
      - name: Build
        run: npm run build
        working-directory: tracker-app
        env:
          VITE_USER_POOL_ID: ${{ secrets.VITE_USER_POOL_ID }}
          VITE_USER_POOL_CLIENT_ID: ${{ secrets.VITE_USER_POOL_CLIENT_ID }}
          VITE_AWS_REGION: ${{ secrets.VITE_AWS_REGION }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: tracker-app/dist
      - id: deployment
        uses: actions/deploy-pages@v4